### ISSUE TITLE
"Traceback"? errors

### ISSUE THREAD

**Issue by hunterhogan** [iteratedecks/fansiteSubmission#4]
I use the same wrapper for both id and to. From time-to-time, I get non-fatal errors from the wrapper, and to me, the errors all look similar. Below are two sets of errors that just happened--one set from each simulator. My token has been removed.

C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize>fansiteSubmission-master\fansiteSims.py --runForever
Namespace(config='fansite_config.txt', limit=None, numSims='100007', numThreads='1', runForever=1, simulator='Tyrant Optimizer', test=0, token='[no]')
Using Tyrant Optimizer version 1.0.3 with 100007 sims per deck
Requesting session id...
 ... started session with id f3d701ab91cb98ad34e88df86d3wbD29
Getting decks...
 ... 50 decks retrieved
Traceback (most recent call last):
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSims.py", line 99, in fansiteTest
    results = simDeck(simulator, deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSims.py", line 51, in simDeck
    results = simulator.simulate(deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSimulator.py", line 45, in simulate
    self.addAchievement(commandArgs, deck["achId"], deck["missionId"])
KeyError: 'missionId'
Traceback (most recent call last):
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSims.py", line 99, in fansiteTest
    results = simDeck(simulator, deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSims.py", line 51, in simDeck
    results = simulator.simulate(deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSimulator.py", line 45, in simulate
    self.addAchievement(commandArgs, deck["achId"], deck["missionId"])
KeyError: 'missionId'
Traceback (most recent call last):
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSims.py", line 99, in fansiteTest
    results = simDeck(simulator, deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSims.py", line 51, in simDeck
    results = simulator.simulate(deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\tyrant_optimize\fansiteSubmission-master\fansiteSimulator.py", line 45, in simulate
    self.addAchievement(commandArgs, deck["achId"], deck["missionId"])
KeyError: 'missionId'
Running tyrant_optimize.exe P5gofn+ifo+jgQgR+iDt "Quest #8" -e 4 -r -t 1 sim 100007
 ... result: 63534/100007, anp=12.8577, time=7
Running tyrant_optimize.exe QVAsBjBmBqCtEDEFJeM3Nu "Mission #339" -t 1 sim 100007
 ... result: 92654/100007, anp=22.3466, time=5
Running tyrant_optimize.exe QHfo+ifw+ifofw+ifvDN+i "Mission #125" -A 178 -r -t 1 sim 100007
 ... result: 8655/100007, anp=1.73088, time=8
Running tyrant_optimize.exe Tdfn+i-Az+o "Quest #15" -e 7 -t 1 sim 100007
 ... result: 96523/100007, anp=23.9173, time=5
Running tyrant_optimize.exe QHCIIf+jJeKPgfgqgvhD "Mission #273" -t 1 sim 100007
 ... result: 76660/100007, anp=18.5259, time=6

---

C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks>fansiteSubmission-master\fansiteSims.py --runForever
Namespace(config='fansite_config.txt', limit=None, numSims='100007', numThreads=None, runForever=1, simulator='iteratedecks', test=0, token=[no]')
Using iteratedecks version 1.0.4 with 100007 sims per deck
Requesting session id...
 ... started session with id 93b4da675c4c8df9983ae1128c3wPft9
Getting decks...
 ... 50 decks retrieved
Running iteratedecks-cli.exe QVB0DwHwIZNLOyg+hBhF -a 209 -m 188 -n 100007 --seed
 ... result: 99951/100007, anp=22.6456, time=17
Running iteratedecks-cli.exe TfO2+q -m 210 -n 100007 --seed
 ... result: 98658/100007, anp=21.9503, time=10
Traceback (most recent call last):
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSims.py", line 99, in fansiteTest
    results = simDeck(simulator, deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSims.py", line 51, in simDeck
    results = simulator.simulate(deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSimulator.py", line 45, in simulate
    self.addAchievement(commandArgs, deck["achId"], deck["missionId"])
KeyError: 'missionId'
Traceback (most recent call last):
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSims.py", line 99, in fansiteTest
    results = simDeck(simulator, deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSims.py", line 51, in simDeck
    results = simulator.simulate(deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSimulator.py", line 45, in simulate
    self.addAchievement(commandArgs, deck["achId"], deck["missionId"])
KeyError: 'missionId'
Running iteratedecks-cli.exe Tghb -Q 9 -b 4 -n 100007 --seed
 ... result: 98435/100007, anp=19.6856, time=12
Traceback (most recent call last):
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSims.py", line 99, in fansiteTest
    results = simDeck(simulator, deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSims.py", line 51, in simDeck
    results = simulator.simulate(deck, args)
  File "C:\Users\Hunter\Documents\Misc\Games\Tyrant\iteratedecks\fansiteSubmission-master\fansiteSimulator.py", line 45, in simulate
    self.addAchievement(commandArgs, deck["achId"], deck["missionId"])
KeyError: 'missionId'
Running iteratedecks-cli.exe Tf-Az+m -m 209 -n 100007 --seed
 ... result: 100005/100007, anp=20.0328, time=7
Running iteratedecks-cli.exe QVIZH0+nvK+i -m 280 -o -n 100007 --seed
 ... result: 93444/100007, anp=21.4572, time=11
Running iteratedecks-cli.exe QVIZfZgqJ9HYHxgFDtfl+i -m 283 -o -n 100007 --seed
 ... result: 77865/100007, anp=16.9637, time=32

**Comment by MrHen** [comment]
Looks like the simulation request was for an achievement without a mission. I assumed all achievements needed to be simulated against a mission...

Not sure what the request was but I know how to fix it so it won't break. I won't get a chance to tweak it until tomorrow but if you want to try, put this code in fansiteSimulator.py:

```
if("missionId" in deck):
    self.addAchievement(commandArgs, deck["achId"], deck["missionId"])
else:
    print("Skipping achievement " + str(deck["achId"]) + " because it has no mission id.")
    return # don't run the simulation
```

Then if you see which one it is breaking on we can update to support it.
